package organization

import "errors"

var (
	ErrOrgNotFound              = errors.New("EBCX-ORGANIZATION-NOT-FOUND")
	ErrOrgVersionConflict       = errors.New("EBCX-ORGANIZATION-VERSION-CONFLICT")
	ErrOrgVersionMonotonic      = errors.New("EBCX-ORGANIZATION-VERSION-MONOTONIC-VIOLATION")
	ErrOrgLevelExceedMax        = errors.New("EBCX-ORGANIZATION-LEVEL-EXCEED-MAX")
	ErrOrgSubtreeLevelExceedMax = errors.New("EBCX-ORGANIZATION-SUBTREE-LEVEL-EXCEED-MAX")
	ErrOrgCycleDetected         = errors.New("EBCX-ORGANIZATION-CYCLE-DETECTED")
	ErrOrgParentNotFound        = errors.New("EBCX-ORGANIZATION-PARENT-NOT-FOUND")
	ErrOrgParentCrossEnterprise = errors.New("EBCX-ORGANIZATION-PARENT-CROSS-ENTERPRISE")
	ErrOrgEnterpriseNotFound    = errors.New("EBCX-ORGANIZATION-ENTERPRISE-NOT-FOUND")
	ErrOrgEnterpriseImmutable   = errors.New("EBCX-ORGANIZATION-ENTERPRISE-IMMUTABLE")
	ErrOrgDuplicateCode         = errors.New("EBCX-ORGANIZATION-DUPLICATE-CODE")
	ErrOrgInvalidName           = errors.New("EBCX-ORGANIZATION-INVALID-NAME")
	ErrOrgInvalidCode           = errors.New("EBCX-ORGANIZATION-INVALID-CODE")
	ErrOrgInvalidCommandID      = errors.New("EBCX-ORGANIZATION-INVALID-COMMAND-ID")
	ErrOrgCommandIDRequired     = errors.New("EBCX-ORGANIZATION-COMMAND-ID-REQUIRED")
	ErrOrgIdempotencyConflict   = errors.New("EBCX-ORGANIZATION-IDEMPOTENCY-CONFLICT")
	ErrOrgUnknownCommand        = errors.New("EBCX-ORGANIZATION-UNKNOWN-COMMAND")
	ErrOrgLevelForbiddenSet     = errors.New("EBCX-ORGANIZATION-LEVEL-FORBIDDEN-SET")
	ErrTenantContextMismatch    = errors.New("EBCX-TENANT-CONTEXT-MISMATCH")
	ErrTenantAccessDenied       = errors.New("EBCX-TENANT-ACCESS-DENIED")
	ErrEvidenceWriteFailed      = errors.New("EBCX-EVIDENCE-WRITE-FAILED")
	ErrOutboxWriteFailed        = errors.New("EBCX-OUTBOX-WRITE-FAILED")
	ErrTransactionCommitFailed  = errors.New("EBCX-TRANSACTION-COMMIT-FAILED")
	ErrIdempotencyRecordFailed  = errors.New("EBCX-IDEMPOTENCY-RECORD-FAILED")
)
